import type { Metadata } from 'next';
import Link from 'next/link';
import { Avatar, ScoreBadge, SectionCard, StageBadge } from '../../../../components/crm-components';
import { getLead } from '../../../../lib/crm-data';
import { PageShell } from '../../../../components/page-shell';
import { LiveConversationPanel } from '../../../../components/live-conversation-panel';
import { loadLiveLeadConversation } from '../../../../lib/live-lead-conversation';
import { LiveFollowUpPlan } from '../../../../components/live-follow-up-plan';
import { LiveProposalSummary } from '../../../../components/live-proposal-summary';
import { LiveDealSummary } from '../../../../components/live-deal-summary';
type LeadPageProps = { params: Promise<{ id: string }> };
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: LeadPageProps): Promise<Metadata> {
  const { id } = await params;
  return { title: getLead(id).name };
}
export default async function LeadPage({ params }: LeadPageProps) {
  const { id } = await params;
  const lead = getLead(id);
  const liveConversation = await loadLiveLeadConversation(id);
  return <PageShell title="Lead details" description="Research, activity, approvals, and contact status for one prospect.">
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><Avatar lead={lead} size="lg" /><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-semibold text-slate-950">{lead.name}</h2><StageBadge stage={lead.stage} /></div><p className="mt-1 text-sm text-slate-500">{lead.role} · <span className="font-medium text-slate-700">{lead.company}</span></p><p className="mt-2 text-xs text-slate-400">{lead.email} · Added via {lead.source}</p></div></div><div className="flex items-center gap-2"><span className="rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-semibold text-amber-700">Demo record</span><Link className="rounded-xl bg-slate-950 px-3 py-2 text-xs font-semibold text-white hover:bg-slate-800" href="/leads">Back to leads</Link></div></div>
      <div className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
        <div className="space-y-6"><SectionCard title="Research" description={`Company context for ${lead.company}.`}><div className="space-y-5 p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.13em] text-slate-400">Overview</p><p className="mt-2 text-sm leading-6 text-slate-600">{lead.research}</p></div><div className="grid gap-4 md:grid-cols-2"><Insight title="Service match" text={lead.serviceMatch} /><Insight title="Portfolio match" text={lead.researchDetails.portfolioMatch} /></div><ResearchList title="Verified signals" items={lead.researchDetails.verifiedSignals.map((item) => `${item.reasoning} · ${item.url}`)} /><ResearchList title="Possible needs (hypotheses)" items={lead.researchDetails.possibleNeeds} /><ResearchList title="Personalization angles" items={lead.researchDetails.personalizationAngles.map((item) => `${item.reasoning} · ${item.url}`)} /><div className="flex flex-wrap items-center gap-2 border-t border-slate-100 pt-4"><span className="text-xs text-slate-400">Research confidence</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{Math.round(lead.researchDetails.confidence * 100)}%</span><span className="text-xs text-slate-400">Evidence-backed · human review required before outreach</span></div></div></SectionCard><SectionCard title="Conversation" description="Inbound and outbound history is shown in chronological order.">{liveConversation.length > 0 ? <LiveConversationPanel messages={liveConversation} /> : <div className="space-y-4 p-5">{lead.conversation.map((message) => <div className={`flex ${message.direction === 'outbound' ? 'justify-end' : 'justify-start'}`} key={`${message.direction}-${message.time}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 ${message.direction === 'outbound' ? 'bg-slate-950 text-white' : 'bg-slate-100 text-slate-700'}`}><p className="text-sm leading-6">{message.text}</p><p className={`mt-2 text-[11px] ${message.direction === 'outbound' ? 'text-slate-300' : 'text-slate-400'}`}>{message.time} · {message.direction === 'outbound' ? 'You' : lead.name}</p></div></div>)}</div>}</SectionCard><LiveFollowUpPlan leadId={id} /></div>
        <div className="space-y-6"><SectionCard title="Fit score" description="Qualification is recorded separately from outreach approval."><div className="p-5"><div className="flex items-end justify-between"><div><p className="text-5xl font-semibold tracking-tight text-slate-950">{lead.score}</p><p className="mt-1 text-xs text-slate-500">out of 100</p></div><ScoreBadge score={lead.score} /></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${lead.score}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-500">Strong fit based on company stage, role, product motion, and stated growth signals.</p></div></SectionCard><LiveProposalSummary leadId={id}/><LiveDealSummary leadId={id}/><SectionCard title="AI activity" description="Every generated result keeps its operation and review state."><div className="space-y-4 p-5">{lead.aiActivity.map((activity) => <div className="flex items-start gap-3" key={activity.label}><span className={`mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${activity.status === 'complete' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{activity.status === 'complete' ? '✓' : '!'}</span><div><p className="text-xs font-semibold text-slate-800">{activity.label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{activity.detail}</p></div></div>)}</div></SectionCard><SectionCard title="Next action"><div className="p-5"><p className="text-sm font-semibold text-slate-900">{lead.nextAction}</p><p className="mt-2 text-xs leading-5 text-slate-500">Keep the decision human-approved. The system will not send or schedule outreach from this view.</p><span className="mt-4 block rounded-xl bg-slate-100 px-4 py-2.5 text-center text-xs font-semibold text-slate-500">Action controls arrive with persistence</span></div></SectionCard></div>
      </div>
    </div>
  </PageShell>;
}

function Insight({ title, text }: Readonly<{ title: string; text: string }>) {
  return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-slate-400">{title}</p><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>;
}
function ResearchList({ title, items }: Readonly<{ title: string; items: readonly string[] }>) { return <div><p className="text-xs font-semibold uppercase tracking-[0.13em] text-slate-400">{title}</p><ul className="mt-2 space-y-2">{items.map((item) => <li className="text-sm leading-6 text-slate-600" key={item}>{item}</li>)}</ul></div>; }
