import { z } from 'zod';
export const replyIntentSchema=z.enum(['POSITIVE','QUESTION','NOT_NOW','NOT_INTERESTED','REFERRAL','OUT_OF_OFFICE','UNSUBSCRIBE','OTHER']);
export type ReplyIntent=z.infer<typeof replyIntentSchema>;
export const recommendedActionSchema=z.enum(['REVIEW_AND_REPLY','PREPARE_MEETING_PATH','ANSWER_QUESTION','NURTURE','CLOSE','PROCESS_REFERRAL','WAIT_FOR_RETURN','SUPPRESS_CONTACT','MANUAL_REVIEW']);
export type RecommendedAction=z.infer<typeof recommendedActionSchema>;
export const replyClassificationSchema=z.strictObject({intent:replyIntentSchema,confidence:z.number().min(0).max(1),summary:z.string().trim().min(1).max(500),reasoning:z.string().trim().min(1).max(500),recommendedAction:recommendedActionSchema,followUpAllowed:z.boolean(),needsReview:z.boolean(),extractedSignals:z.strictObject({meetingInterest:z.boolean(),asksForMoreInfo:z.boolean(),timingDelay:z.boolean(),referralMentioned:z.boolean(),unsubscribeRequested:z.boolean()})});
export type ReplyClassification=z.infer<typeof replyClassificationSchema>;
export const replyClassificationJsonSchema={type:'object',additionalProperties:false,properties:{intent:{type:'string',enum:replyIntentSchema.options},confidence:{type:'number'},summary:{type:'string'},reasoning:{type:'string'},recommendedAction:{type:'string',enum:recommendedActionSchema.options},followUpAllowed:{type:'boolean'},needsReview:{type:'boolean'},extractedSignals:{type:'object',additionalProperties:false,properties:{meetingInterest:{type:'boolean'},asksForMoreInfo:{type:'boolean'},timingDelay:{type:'boolean'},referralMentioned:{type:'boolean'},unsubscribeRequested:{type:'boolean'}},required:['meetingInterest','asksForMoreInfo','timingDelay','referralMentioned','unsubscribeRequested']}},required:['intent','confidence','summary','reasoning','recommendedAction','followUpAllowed','needsReview','extractedSignals']} as const;
export type ReplyMessageContext=Readonly<{latestMessage:{id:string;body:string;subject:string|null;receivedAt:string};recentContext:readonly {direction:'inbound'|'outbound';body:string}[];lead:{name:string;role:string|null;stage:string};company:{name:string}}>;
export interface ReplyClassificationProvider { readonly provider:'openai'|'ollama'; readonly model:string; readonly promptVersion:string; classifyReply(input:ReplyMessageContext):Promise<unknown>; }
export interface ReplyClassificationStore { findActive(workspaceId:string,messageId:string,promptVersion:string):Promise<ReplyClassificationRecord|null>; create(workspaceId:string,input:ReplyClassificationCreate):Promise<ReplyClassificationRecord>; recordRun(workspaceId:string,run:Readonly<Record<string,unknown>>):Promise<void>; recordActivity(workspaceId:string,type:string,details:Readonly<Record<string,unknown>>,effectKey:string,leadId:string,companyId:string,actorId?:string):Promise<void>; }
export type ReplyClassificationRecord=Readonly<{id:string;workspaceId:string;conversationId:string;messageId:string;leadId:string;intent:ReplyIntent|null;confidence:number|null;summary:string|null;reasoning:string|null;recommendedAction:RecommendedAction|null;followUpAllowed:boolean;needsReview:boolean;provider:string;model:string;promptVersion:string;version:number;createdAt:string}>;
export type ReplyClassificationCreate=Omit<ReplyClassificationRecord,'id'|'createdAt'>;
export function deterministicIntent(body:string):ReplyIntent|null { const value=body.toLowerCase(); if(/\b(unsubscribe|remove me|stop emailing|stop contacting|do not contact|don't contact)\b/.test(value)) return 'UNSUBSCRIBE'; if(/\b(out of office|automatic reply|auto-reply|currently away|on leave)\b/.test(value)) return 'OUT_OF_OFFICE'; return null; }
export function effectiveReplyIntent(human:ReplyIntent|null,confirmed:ReplyIntent|null,latest:ReplyIntent|null):ReplyIntent|null{return human??confirmed??latest;}
export function getEffectiveReplyIntent(input:Readonly<{humanOverride?:ReplyIntent|null;confirmedAi?:ReplyIntent|null;unresolvedAi?:ReplyIntent|null}>):ReplyIntent|null{return effectiveReplyIntent(input.humanOverride??null,input.confirmedAi??null,input.unresolvedAi??null);}
export function classifyRouting(intent:ReplyIntent):'interested'|'replied'|'suppressed'{if(intent==='POSITIVE')return 'interested';if(intent==='UNSUBSCRIBE')return 'suppressed';return 'replied';}
export async function classifyInboundReply(provider:ReplyClassificationProvider,store:ReplyClassificationStore,input:{workspaceId:string;conversationId:string;messageId:string;leadId:string;companyId:string;context:ReplyMessageContext;},options:{regenerate?:boolean}={}){const deterministic=deterministicIntent(input.context.latestMessage.body);const key=`${input.messageId}:${provider.promptVersion}`;if(!options.regenerate){const existing=await store.findActive(input.workspaceId,input.messageId,provider.promptVersion);if(existing)return existing;}const started=Date.now();let parsed:ReplyClassification|null=null;let error='';if(deterministic==='UNSUBSCRIBE'){parsed={intent:'UNSUBSCRIBE',confidence:1,summary:'The recipient requested no further contact.',reasoning:'The reply contains an explicit opt-out request.',recommendedAction:'SUPPRESS_CONTACT',followUpAllowed:false,needsReview:false,extractedSignals:{meetingInterest:false,asksForMoreInfo:false,timingDelay:false,referralMentioned:false,unsubscribeRequested:true}};}else{for(let attempt=0;attempt<2&&!parsed;attempt++){try{if(!provider.classifyReply)throw new Error('Reply classification is not supported by this provider');const raw=await provider.classifyReply(input.context);parsed=replyClassificationSchema.parse(raw);if(parsed.intent==='UNSUBSCRIBE')parsed={...parsed,followUpAllowed:false,needsReview:false,recommendedAction:'SUPPRESS_CONTACT',extractedSignals:{...parsed.extractedSignals,unsubscribeRequested:true}};if(parsed.confidence<.75)parsed={...parsed,needsReview:true};}catch(cause){error=cause instanceof Error?cause.message:'Invalid classification output';await store.recordRun(input.workspaceId,{operation:'reply_classification',operationKey:`${key}:attempt-${attempt+1}`,leadId:input.leadId,companyId:input.companyId,conversationId:input.conversationId,messageId:input.messageId,provider:provider.provider,model:provider.model,promptVersion:provider.promptVersion,input:{messageId:input.messageId,attempt:attempt+1},output:null,confidence:null,status:attempt===1?'invalid':'failed',error,durationMs:Date.now()-started});}}}
if(!parsed){await store.recordActivity(input.workspaceId,'reply_classification_failed',{message_id:input.messageId,conversation_id:input.conversationId},`reply_classification_failed:${input.messageId}`,input.leadId,input.companyId);return store.create(input.workspaceId,{workspaceId:input.workspaceId,conversationId:input.conversationId,messageId:input.messageId,leadId:input.leadId,intent:null,confidence:null,summary:null,reasoning:null,recommendedAction:'MANUAL_REVIEW',followUpAllowed:false,needsReview:true,provider:provider.provider,model:provider.model,promptVersion:provider.promptVersion,version:1});}
await store.recordRun(input.workspaceId,{operation:'reply_classification',operationKey:`${key}:success`,leadId:input.leadId,companyId:input.companyId,conversationId:input.conversationId,messageId:input.messageId,provider:provider.provider,model:provider.model,promptVersion:provider.promptVersion,input:{messageId:input.messageId},output:parsed,confidence:parsed.confidence,status:'succeeded',durationMs:Date.now()-started});const created=await store.create(input.workspaceId,{workspaceId:input.workspaceId,conversationId:input.conversationId,messageId:input.messageId,leadId:input.leadId,intent:parsed.intent,confidence:parsed.confidence,summary:parsed.summary,reasoning:parsed.reasoning,recommendedAction:parsed.recommendedAction,followUpAllowed:false,needsReview:parsed.needsReview,provider:provider.provider,model:provider.model,promptVersion:provider.promptVersion,version:options.regenerate?2:1});await store.recordActivity(input.workspaceId,'reply_classified',{message_id:input.messageId,intent:parsed.intent,confidence:parsed.confidence},`reply_classified:${created.id}`,input.leadId,input.companyId);return created;}
