import { describe, expect, it, vi } from 'vitest';
import { CompanyResearchAgent, WebsiteResearchFetcher, assertSafeResearchUrl, type CompanyResearch } from '@client-engine/ai';

const output: CompanyResearch = { companySummary: 'A public SaaS company', productSummary: 'Invoice automation', targetCustomer: 'Small finance teams', apparentStage: 'Self-serve', recommendedService: 'AI SaaS development', portfolioMatch: 'AI SaaS', verifiedSignals: [{ url: 'https://example.com', reasoning: 'The homepage describes invoice automation.' }], possibleNeeds: ['May benefit from more automation'], personalizationAngles: [{ url: 'https://example.com/about', reasoning: 'The team describes a self-serve workflow.' }], confidence: 0.9, usableForOutreach: true, needsReview: false };
const htmlResponse = (body = '<html><body><h1>InvoiceAI</h1><p>Automated invoicing.</p></body></html>', init?: ResponseInit) => new Response(body, { status: 200, headers: { 'content-type': 'text/html' }, ...init });
const resolver = async (host: string) => host === 'localhost' ? ['127.0.0.1'] : ['93.184.216.34'];

describe('bounded company research', () => {
  it('fetches bounded public pages and normalizes HTML', async () => { const fetchImpl = vi.fn(async () => htmlResponse()); const docs = await new WebsiteResearchFetcher({ fetchImpl, resolveHostname: resolver, maxPages: 3 }).fetchCompany('https://example.com'); expect(docs).toHaveLength(3); expect(docs[0].text).toContain('InvoiceAI'); expect(docs[0].text).not.toContain('<h1>'); });
  it('reuses fresh company research for multiple leads', async () => { let saved: unknown; const cache = { get: vi.fn(async () => saved as never), save: vi.fn(async (run: unknown) => { saved = run; }) }; const provider = { provider: 'ollama' as const, model: 'local', promptVersion: 'v1', qualifyLead: vi.fn(), researchCompany: vi.fn(async () => output) }; const agent = new CompanyResearchAgent(provider, new WebsiteResearchFetcher({ fetchImpl: async () => htmlResponse(), resolveHostname: resolver, maxPages: 1 }), cache); await agent.research({ companyId: 'c1', company: { name: 'InvoiceAI', domain: 'example.com' } }); await agent.research({ companyId: 'c1', company: { name: 'InvoiceAI', domain: 'example.com' } }); expect(provider.researchCompany).toHaveBeenCalledTimes(1); });
  it('routes inaccessible sites to review', async () => { const run = await new CompanyResearchAgent({ provider: 'ollama', model: 'local', promptVersion: 'v1', qualifyLead: vi.fn(), researchCompany: vi.fn() }, new WebsiteResearchFetcher({ fetchImpl: async () => new Response('', { status: 500 }), resolveHostname: resolver })).research({ companyId: 'c1', company: { name: 'X', domain: 'example.com' } }); expect(run.status).toBe('needs_review'); });
  it('rejects oversized responses, timeouts, excessive redirects and unsafe URLs', async () => { await expect(new WebsiteResearchFetcher({ maxResponseBytes: 2, fetchImpl: async () => htmlResponse('large'), resolveHostname: resolver }).fetchCompany('example.com')).resolves.toEqual([]); const timeout = new WebsiteResearchFetcher({ timeoutMs: 1, fetchImpl: async (_u, init) => { await new Promise((resolve) => setTimeout(resolve, 5)); if (init?.signal?.aborted) throw new Error('aborted'); return htmlResponse(); }, resolveHostname: resolver }); await expect(timeout.fetchCompany('example.com')).resolves.toEqual([]); const redirect = new WebsiteResearchFetcher({ maxRedirects: 0, fetchImpl: async () => new Response('', { status: 302, headers: { location: 'https://example.com/about' } }), resolveHostname: resolver }); await expect(redirect.fetchCompany('example.com')).resolves.toEqual([]); });
  it.each(['http://localhost', 'http://169.254.169.254', 'file:///tmp/a'])('rejects unsafe research URL %s', async (url) => { await expect(assertSafeResearchUrl(url, resolver)).rejects.toThrow(); });
  it('marks invalid and low-confidence AI results for review and never sends outreach', async () => { const provider = { provider: 'ollama' as const, model: 'local', promptVersion: 'v1', qualifyLead: vi.fn(), researchCompany: vi.fn(async () => ({ ...output, confidence: 0.2, needsReview: true, usableForOutreach: true })) }; const send = vi.fn(); const run = await new CompanyResearchAgent(provider, new WebsiteResearchFetcher({ fetchImpl: async () => htmlResponse(), resolveHostname: resolver, maxPages: 1 })).research({ companyId: 'c1', company: { name: 'X', domain: 'example.com' } }); expect(run.status).toBe('needs_review'); expect(send).not.toHaveBeenCalled(); });
  it('does not mark hypotheses as verified facts', () => expect(output.verifiedSignals.some((item) => item.reasoning.toLowerCase().includes('may benefit'))).toBe(false));
});
