import { describe, expect, it } from 'vitest';
import { FollowUpGenerationService, validateFollowUpEvidence } from '@client-engine/ai';
import type { AIProvider } from '@client-engine/ai';

const research = { companySummary:'A company',productSummary:'A product',targetCustomer:'Founders',apparentStage:'early',recommendedService:'AI SaaS product development',portfolioMatch:'',verifiedSignals:[{url:'https://example.com/about',reasoning:'Public fact'}],possibleNeeds:['may need help'],personalizationAngles:[{url:'https://example.com/product',reasoning:'Product detail'}],confidence:.9,usableForOutreach:true,needsReview:false };
const input = { workspaceId:'w',followUpTaskId:'t',leadId:'l',companyId:'c',conversationId:'v',originalDeliveryId:'d',lead:{name:'Alex',role:'Founder'},company:{name:'Example',domain:'example.com'},task:{sequenceStep:1,purpose:'VALUE_FOLLOW_UP' as const},originalOutreach:{subject:'Hello',body:'Original body'},priorOutbound:[],research,serviceMatch:null,portfolioMatch:null,contextVersion:'r1' };
type Stored = { id:string; generationKey:string; version:number; evidenceRefs: readonly { sourceUrl:string }[] } & Record<string, unknown>;
class FakeStore { rows: Stored[]=[]; async findByGenerationKey(_w:string,k:string){return this.rows.find(x=>x.generationKey===k)??null;} async listByTask(){return this.rows;} async create(_w:string,x:Record<string, unknown>){const row={...x,id:`d${this.rows.length+1}`} as Stored;this.rows.push(row);return row;} async supersedeActive(){} }
class FakeRuns { runs: Record<string, unknown>[]=[]; async record(_w:string,x:Record<string, unknown>){this.runs.push(x);} }
const provider=(outputs:unknown[]): AIProvider => ({provider:'ollama',model:'local',promptVersion:'follow-up.v1',qualifyLead:async()=>({} as never),researchCompany:async()=>({} as never),generateFollowUp:async()=>outputs.shift()});
const valid={subject:'A useful note',body:'One useful observation about your product and a quick way to compare notes. Open to a short walkthrough?',purpose:'VALUE_FOLLOW_UP',angle:'Product observation',evidenceRefs:[{type:'verified_signal',sourceUrl:'https://example.com/about',claim:'Public fact'}],serviceMatch:null,portfolioMatch:null,confidence:.9,usableForFollowUp:true,needsReview:false,warnings:[]};
describe('follow-up draft generation',()=>{
 it('persists evidence-grounded drafts and reuses normal retries',async()=>{const store=new FakeStore();const runs=new FakeRuns();const svc=new FollowUpGenerationService(provider([valid]),store,runs);const first=await svc.generate(input);const second=await svc.generate(input);expect(first).toEqual(second);expect(store.rows).toHaveLength(1);expect((first as {evidenceRefs:readonly {sourceUrl:string}[]}).evidenceRefs[0].sourceUrl).toBe('https://example.com/about');});
 it('allows one repair attempt and safely fails after the second',async()=>{const store=new FakeStore();const runs=new FakeRuns();const svc=new FollowUpGenerationService(provider(['bad','still bad']),store,runs);await expect(svc.generate(input)).rejects.toThrow('needs review');expect(runs.runs).toHaveLength(2);expect(store.rows).toHaveLength(0);});
 it('routes low confidence and unsupported evidence to review',()=>{const result=validateFollowUpEvidence({...valid, purpose:'VALUE_FOLLOW_UP' as const, confidence:.3,evidenceRefs:[]},input);expect(result.needsReview).toBe(true);expect(result.usableForFollowUp).toBe(false);});
 it('does not persist when final eligibility recheck fails',async()=>{const store=new FakeStore();const runs=new FakeRuns();const svc=new FollowUpGenerationService(provider([valid]),store,runs);const result=await svc.generate(input,{beforePersist:async()=>false});expect(result).toBeNull();expect(store.rows).toHaveLength(0);});
});
