import type { AIProvider } from '../qualification';
import { WebsiteResearchFetcher } from './fetcher';
import { type CompanyResearch } from './index';

export type ResearchLifecycle = 'qualified' | 'researching' | 'researched' | 'needs_review';
export type CompanyResearchRun = Readonly<{ companyId: string; company: { name: string; domain: string }; status: ResearchLifecycle; research: CompanyResearch | null; documents: readonly { url: string; text: string }[]; error?: string }>;
export type ResearchCache = Readonly<{ get(companyId: string, freshWithinMs: number): Promise<CompanyResearchRun | null>; save(run: CompanyResearchRun): Promise<void> }>;
export type ResearchRunStore = Readonly<{ record(workspaceId: string, run: { operation: 'company_research'; operationKey: string; companyId: string; provider: string; model: string; promptVersion: string; input: Readonly<Record<string, unknown>>; output: Readonly<Record<string, unknown>> | null; confidence: number | null; status: 'succeeded' | 'failed' | 'invalid'; error?: string | null }): Promise<void> }>;
export class CompanyResearchAgent {
  constructor(private readonly provider: AIProvider, private readonly fetcher: WebsiteResearchFetcher, private readonly cache?: ResearchCache, private readonly freshWithinMs = 86_400_000, private readonly runStore?: ResearchRunStore) {}
  async research(input: { companyId: string; company: { name: string; domain: string }; workspaceId?: string }): Promise<CompanyResearchRun> { const cached = await this.cache?.get(input.companyId, this.freshWithinMs); if (cached) return cached; let documents: readonly { url: string; text: string }[] = []; try { documents = await this.fetcher.fetchCompany(input.company.domain); if (!documents.length) { const run = { ...input, status: 'needs_review' as const, research: null, documents, error: 'No accessible public pages' }; await this.cache?.save(run); return run; } const output = await this.provider.researchCompany({ company: input.company, documents }); const run = { ...input, status: output.needsReview ? 'needs_review' as const : 'researched' as const, research: output, documents }; await this.cache?.save(run); if (input.workspaceId) await this.runStore?.record(input.workspaceId, { operation: 'company_research', operationKey: `company-research:${input.companyId}`, companyId: input.companyId, provider: this.provider.provider, model: this.provider.model, promptVersion: this.provider.promptVersion, input: { company: input.company, urls: documents.map((document) => document.url) }, output, confidence: output.confidence, status: run.status === 'researched' ? 'succeeded' : 'invalid' }); return run; } catch (error) { const run = { ...input, status: 'needs_review' as const, research: null, documents, error: error instanceof Error ? error.message : 'Research failed' }; await this.cache?.save(run); if (input.workspaceId) await this.runStore?.record(input.workspaceId, { operation: 'company_research', operationKey: `company-research:${input.companyId}`, companyId: input.companyId, provider: this.provider.provider, model: this.provider.model, promptVersion: this.provider.promptVersion, input: { company: input.company, urls: documents.map((document) => document.url) }, output: null, confidence: null, status: 'failed', error: run.error }); return run; } }
}
