import { lookup } from 'node:dns/promises';

export type ResearchFetchConfig = Readonly<{ maxPages?: number; timeoutMs?: number; maxResponseBytes?: number; maxRedirects?: number; maxTextChars?: number; fetchImpl?: typeof fetch; resolveHostname?: (hostname: string) => Promise<readonly string[]> }>;
export type FetchedResearch = Readonly<{ url: string; text: string }>;
const htmlStrip = (html: string) => html.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, ' ').replace(/<[^>]+>/g, ' ').replace(/&nbsp;|&amp;|&lt;|&gt;/g, ' ').replace(/\s+/g, ' ').trim();
const privateIp = (ip: string) => ip === '127.0.0.1' || ip === '::1' || ip === '0.0.0.0' || /^10\./.test(ip) || /^192\.168\./.test(ip) || /^172\.(1[6-9]|2\d|3[01])\./.test(ip) || /^169\.254\./.test(ip) || /^fc|^fd/i.test(ip) || /^fe80:/i.test(ip);
export function assertSafeResearchUrl(raw: string, resolveHostname: (hostname: string) => Promise<readonly string[]>): Promise<URL> { return (async () => { let url: URL; try { url = new URL(raw); } catch { throw new Error('Invalid research URL'); } if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Unsupported research URL protocol'); if (url.username || url.password) throw new Error('Research URL credentials are forbidden'); if (url.hostname === 'metadata.google.internal' || url.hostname === 'metadata.google' || url.hostname === '169.254.169.254' || privateIp(url.hostname)) throw new Error('Private or cloud metadata research address blocked'); const addresses = await resolveHostname(url.hostname); if (addresses.some(privateIp)) throw new Error('Private or loopback research address blocked'); return url; })(); }
export class WebsiteResearchFetcher {
  private readonly config: Required<Omit<ResearchFetchConfig, 'fetchImpl' | 'resolveHostname'>> & Pick<ResearchFetchConfig, 'fetchImpl' | 'resolveHostname'>;
  constructor(config: ResearchFetchConfig = {}) { this.config = { maxPages: 6, timeoutMs: 8000, maxResponseBytes: 1_000_000, maxRedirects: 2, maxTextChars: 40_000, ...config }; }
  async fetchCompany(domain: string): Promise<FetchedResearch[]> { const base = await assertSafeResearchUrl(domain.startsWith('http') ? domain : `https://${domain}`, this.config.resolveHostname ?? (async (host) => (await lookup(host, { all: true })).map((entry) => entry.address))); const paths = ['', '/about', '/product', '/features', '/pricing', '/customers', '/case-studies', '/jobs'].slice(0, this.config.maxPages); const documents: FetchedResearch[] = []; let remaining = this.config.maxTextChars; for (const path of paths) { try { const doc = await this.fetchOne(new URL(path, base)); if (doc && remaining > 0) { const text = doc.text.slice(0, remaining); documents.push({ url: doc.url, text }); remaining -= text.length; } } catch { /* inaccessible optional pages are skipped */ } } return documents; }
  private async fetchOne(initial: URL): Promise<FetchedResearch | null> { let url = initial; for (let redirects = 0; redirects <= this.config.maxRedirects; redirects += 1) { await assertSafeResearchUrl(url.toString(), this.config.resolveHostname ?? (async (host) => (await lookup(host, { all: true })).map((entry) => entry.address))); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.config.timeoutMs); let response: Response; try { response = await (this.config.fetchImpl ?? fetch)(url, { redirect: 'manual', signal: controller.signal }); } finally { clearTimeout(timer); } if (response.status >= 300 && response.status < 400) { const location = response.headers.get('location'); if (!location || redirects === this.config.maxRedirects) throw new Error('Redirect limit exceeded'); url = new URL(location, url); continue; } if (!response.ok) return null; const length = Number(response.headers.get('content-length')); if (Number.isFinite(length) && length > this.config.maxResponseBytes) throw new Error('Response size limit exceeded'); const body = await response.text(); if (new TextEncoder().encode(body).byteLength > this.config.maxResponseBytes) throw new Error('Response size limit exceeded'); const text = htmlStrip(body).slice(0, this.config.maxTextChars); return text ? { url: url.toString(), text } : null; } return null; }
}
