'use client';
import { useState } from 'react';
import { approveFollowUpDraftAction, editFollowUpDraftAction, generateFollowUpDraftAction, regenerateFollowUpDraftAction, rejectFollowUpDraftAction } from '../app/actions/follow-up-drafts';
export function FollowUpDraftActions({ taskId, draftId, status }: Readonly<{ taskId: string; draftId?: string; status?: string }>) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function run(fn: () => Promise<{ ok: boolean; error?: string }>) { setBusy(true); setError(null); const result = await fn(); setBusy(false); if (!result.ok) setError(result.error ?? 'Action failed'); }
  async function edit() { if (!draftId) return; const subject = window.prompt('Subject'); const body = window.prompt('Body'); if (subject && body) await run(() => editFollowUpDraftAction(draftId, subject, body)); }
  return <div className="mt-4 flex flex-wrap gap-2">{!draftId && <button disabled={busy} onClick={() => void run(() => generateFollowUpDraftAction(taskId))} className="rounded-md bg-slate-900 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Generate Draft</button>}{draftId && status === 'ready_for_review' && <><button disabled={busy} onClick={() => void run(() => approveFollowUpDraftAction(draftId))} className="rounded-md bg-emerald-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Approve</button><button disabled={busy} onClick={() => void run(() => rejectFollowUpDraftAction(draftId))} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold disabled:opacity-50">Reject</button><button disabled={busy} onClick={() => void edit()} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold disabled:opacity-50">Edit</button></>}{draftId && <button disabled={busy} onClick={() => void run(() => regenerateFollowUpDraftAction(taskId))} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-semibold disabled:opacity-50">Regenerate</button>}{error && <p className="basis-full text-xs text-red-700">{error}</p>}</div>;
}
