'use client';
import { useState, useTransition } from 'react';
import { approveOutreachAction, editOutreachAction, rejectOutreachAction, regenerateOutreachAction } from '../app/actions/outreach';
import { prepareDeliveryAction } from '../app/actions/delivery';
import { markDeliverySentAction } from '../app/actions/delivery';

export function PrepareDeliveryButton({ draftId }: Readonly<{ draftId: string }>) { const [pending,startTransition]=useTransition(); const [message,setMessage]=useState(''); return <div className="mt-3"><button disabled={pending} type="button" onClick={()=>startTransition(async()=>{const result=await prepareDeliveryAction(draftId);setMessage(result.ok?'Delivery prepared':result.error??'Unable to prepare delivery');})} className="rounded-md bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-50">Prepare delivery</button>{message&&<p role="status" className="mt-2 text-xs text-slate-500">{message}</p>}</div>; }
export function MarkSentButton({ deliveryId }: Readonly<{ deliveryId: string }>) { const [pending,startTransition]=useTransition(); const [message,setMessage]=useState(''); return <div className="mt-3"><button disabled={pending} type="button" onClick={()=>startTransition(async()=>{const result=await markDeliverySentAction(deliveryId);setMessage(result.ok?'Marked sent':result.error??'Unable to mark sent');})} className="rounded-md border px-3 py-2 text-sm disabled:opacity-50">Mark sent</button>{message&&<p role="status" className="mt-2 text-xs text-slate-500">{message}</p>}</div>; }

export function OutreachReviewActions({ draftId, subject, body }: Readonly<{ draftId: string; subject: string; body: string }>) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(''); const [editing, setEditing] = useState(false); const [nextSubject, setNextSubject] = useState(subject); const [nextBody, setNextBody] = useState(body);
  const run = (action: () => Promise<{ ok: boolean; error?: string }>) => startTransition(async () => { setMessage(''); const result = await action(); setMessage(result.ok ? 'Saved' : result.error ?? 'Unable to save'); });
  return <div className="mt-4 space-y-3"><div className="flex flex-wrap gap-2"><button disabled={pending} type="button" onClick={() => run(() => approveOutreachAction(draftId))} className="rounded-md bg-slate-950 px-3 py-2 text-sm text-white disabled:opacity-50">Approve</button><button disabled={pending} type="button" onClick={() => run(() => rejectOutreachAction(draftId))} className="rounded-md border px-3 py-2 text-sm disabled:opacity-50">Reject</button><button disabled={pending} type="button" onClick={() => run(() => regenerateOutreachAction(draftId))} className="rounded-md border px-3 py-2 text-sm disabled:opacity-50">Regenerate</button><button disabled={pending} type="button" onClick={() => setEditing((value) => !value)} className="rounded-md border px-3 py-2 text-sm disabled:opacity-50">Edit</button></div>{editing && <div className="space-y-2"><input value={nextSubject} onChange={(event) => setNextSubject(event.target.value)} maxLength={120} className="w-full rounded-md border px-3 py-2 text-sm" aria-label="Subject" /><textarea value={nextBody} onChange={(event) => setNextBody(event.target.value)} maxLength={1500} rows={6} className="w-full rounded-md border px-3 py-2 text-sm" aria-label="Body" /><button disabled={pending} type="button" onClick={() => run(async () => { const result = await editOutreachAction(draftId, nextSubject, nextBody); if (result.ok) setEditing(false); return result; })} className="rounded-md bg-blue-600 px-3 py-2 text-sm text-white disabled:opacity-50">Save edit</button></div>}{message && <p role="status" className="text-xs text-slate-500">{message}</p>}</div>;
}
