import type { SupabaseClient } from '@supabase/supabase-js';
import type { OutreachActivity, OutreachDraftCreate, OutreachDraftRecord, OutreachDraftStatus, OutreachDraftStore } from './index';
import { assertOutreachTransition } from './index';

function map(row: Record<string, unknown>): OutreachDraftRecord {
  return { id: String(row.id), workspaceId: String(row.workspace_id), leadId: String(row.lead_id), companyId: String(row.company_id), campaignId: row.campaign_id ? String(row.campaign_id) : null, researchVersion: String(row.research_version), version: Number(row.version), subject: String(row.subject), body: String(row.body), personalizationSourceType: row.personalization_source_type as OutreachDraftRecord['personalizationSourceType'], personalizationSourceUrl: row.personalization_source_url ? String(row.personalization_source_url) : null, serviceMatch: row.service_match ? String(row.service_match) : null, portfolioMatch: row.portfolio_match ? String(row.portfolio_match) : null, confidence: Number(row.confidence), warnings: Array.isArray(row.warnings) ? row.warnings.map(String) : [], provider: String(row.provider), model: String(row.model), promptVersion: String(row.prompt_version), status: row.status as OutreachDraftStatus, rejectionReason: row.rejection_reason ? String(row.rejection_reason) : null, approvedAt: row.approved_at ? String(row.approved_at) : null, createdAt: String(row.created_at), updatedAt: String(row.updated_at) };
}
export class SupabaseOutreachDraftStore implements OutreachDraftStore {
  constructor(private readonly client: SupabaseClient) {}
  async findByGenerationKey(workspaceId: string, key: string) { const { data, error } = await this.client.from('outreach_drafts').select('*').eq('workspace_id', workspaceId).eq('generation_key', key).maybeSingle(); if (error) throw new Error(error.message); return data ? map(data) : null; }
  async listByLead(workspaceId: string, leadId: string) { const { data, error } = await this.client.from('outreach_drafts').select('*').eq('workspace_id', workspaceId).eq('lead_id', leadId).order('version', { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map(map); }
  async listReady(workspaceId: string) { const { data, error } = await this.client.from('outreach_drafts').select('*').eq('workspace_id', workspaceId).eq('status', 'ready_for_review').order('created_at', { ascending: false }); if (error) throw new Error(error.message); return (data ?? []).map(map); }
  async create(workspaceId: string, key: string, draft: OutreachDraftCreate) { const { data, error } = await this.client.from('outreach_drafts').insert({ workspace_id: workspaceId, generation_key: key, lead_id: draft.leadId, company_id: draft.companyId, campaign_id: draft.campaignId, research_version: draft.researchVersion, version: draft.version, subject: draft.subject, body: draft.body, personalization_source_type: draft.personalizationSourceType, personalization_source_url: draft.personalizationSourceUrl, service_match: draft.serviceMatch, portfolio_match: draft.portfolioMatch, confidence: draft.confidence, warnings: draft.warnings, provider: draft.provider, model: draft.model, prompt_version: draft.promptVersion, status: draft.status }).select('*').single(); if (error) throw new Error(error.message); return map(data); }
  async updateStatus(workspaceId: string, id: string, status: OutreachDraftStatus, reason?: string, actorUserId?: string) { const current = await this.client.from('outreach_drafts').select('*').eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); if (current.error) throw new Error(current.error.message); if (!current.data) throw new Error('Draft not found'); const row = map(current.data); if (row.status === status) return; assertOutreachTransition(row.status, status); const { error } = await this.client.from('outreach_drafts').update({ status, rejection_reason: reason ?? null, approved_at: status === 'approved' ? new Date().toISOString() : null, approved_by: status === 'approved' ? actorUserId ?? null : null, updated_at: new Date().toISOString() }).eq('workspace_id', workspaceId).eq('id', id).eq('status', row.status); if (error) throw new Error(error.message); }
  async edit(workspaceId: string, id: string, subject: string, body: string, actorUserId?: string) { if (subject.trim().length < 1 || subject.trim().length > 120 || body.trim().length < 1 || body.trim().length > 1500) throw new Error('Subject or body is outside the allowed length'); const current = await this.client.from('outreach_drafts').select('*').eq('workspace_id', workspaceId).eq('id', id).maybeSingle(); if (current.error) throw new Error(current.error.message); if (!current.data) throw new Error('Draft not found'); const row=map(current.data); if (row.status !== 'ready_for_review' && row.status !== 'draft') throw new Error('Only review drafts can be edited'); const history=await this.listByLead(workspaceId,row.leadId); const { data, error } = await this.client.from('outreach_drafts').insert({ workspace_id:workspaceId, generation_key:`manual-edit:${row.id}:${row.version+1}`, lead_id:row.leadId, company_id:row.companyId, campaign_id:row.campaignId, research_version:row.researchVersion, version:Math.max(...history.map(item=>item.version))+1, subject:subject.trim(), body:body.trim(), personalization_source_type:row.personalizationSourceType, personalization_source_url:row.personalizationSourceUrl, service_match:row.serviceMatch, portfolio_match:row.portfolioMatch, confidence:row.confidence, warnings:row.warnings, provider:row.provider, model:row.model, prompt_version:row.promptVersion, status:'ready_for_review' }).select('*').single(); if (error) throw new Error(error.message); await this.recordActivity(workspaceId,{draftId:String(data.id),leadId:row.leadId,companyId:row.companyId,activityType:'outreach_edited',effectKey:`outreach_edited:${data.id}`,details:{version:Number(data.version),previousDraftId:row.id},actorUserId}); return map(data); }
  async recordActivity(workspaceId: string, activity: OutreachActivity) { const { error } = await this.client.from('activities').upsert({ workspace_id:workspaceId, lead_id:activity.leadId, company_id:activity.companyId, actor_kind:activity.actorUserId ? 'operator' : 'system', actor_user_id:activity.actorUserId ?? null, activity_type:activity.activityType, effect_key:activity.effectKey, details:{...activity.details,draft_id:activity.draftId} }, { onConflict:'workspace_id,effect_key', ignoreDuplicates:true }); if (error) throw new Error(error.message); }
}
