import type { SupabaseClient } from '@supabase/supabase-js';
import type { FollowUpDraftActivity, FollowUpDraftCreate, FollowUpDraftRecord, FollowUpDraftStatus, FollowUpDraftStore } from './index';
import { assertFollowUpDraftTransition } from './index';
const map=(r:Record<string,unknown>):FollowUpDraftRecord=>({id:String(r.id),workspaceId:String(r.workspace_id),followUpTaskId:String(r.follow_up_task_id),leadId:String(r.lead_id),companyId:r.company_id?String(r.company_id):null,conversationId:String(r.conversation_id),originalDeliveryId:String(r.original_delivery_id),sequenceStep:Number(r.sequence_step),purpose:r.purpose as FollowUpDraftRecord['purpose'],generationKey:String(r.generation_key),contextVersion:String(r.context_version),version:Number(r.version),subject:String(r.subject),body:String(r.body),status:r.status as FollowUpDraftStatus,confidence:Number(r.confidence),needsReview:Boolean(r.needs_review),warnings:Array.isArray(r.warnings)?r.warnings.map(String):[],evidenceRefs:Array.isArray(r.evidence_refs)?r.evidence_refs as FollowUpDraftRecord['evidenceRefs']:[],conversationRefs:Array.isArray(r.conversation_refs)?r.conversation_refs.map(String):[],serviceMatch:r.service_match?String(r.service_match):null,portfolioMatch:r.portfolio_match?String(r.portfolio_match):null,provider:String(r.provider),model:String(r.model),promptVersion:String(r.prompt_version),approvedAt:r.approved_at?String(r.approved_at):null,approvedBy:r.approved_by?String(r.approved_by):null,rejectedAt:r.rejected_at?String(r.rejected_at):null,rejectionReason:r.rejection_reason?String(r.rejection_reason):null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)});
export class SupabaseFollowUpDraftStore implements FollowUpDraftStore {
 constructor(private client:SupabaseClient){}
 async findById(ws:string,id:string){const q=await this.client.from('follow_up_drafts').select('*').eq('workspace_id',ws).eq('id',id).maybeSingle();if(q.error)throw new Error(q.error.message);return q.data?map(q.data):null;}
 async findByGenerationKey(ws:string,key:string){const q=await this.client.from('follow_up_drafts').select('*').eq('workspace_id',ws).eq('generation_key',key).maybeSingle();if(q.error)throw new Error(q.error.message);return q.data?map(q.data):null;}
 async listByTask(ws:string,task:string){const q=await this.client.from('follow_up_drafts').select('*').eq('workspace_id',ws).eq('follow_up_task_id',task).order('version',{ascending:false});if(q.error)throw new Error(q.error.message);return(q.data??[]).map(map);}
 async create(ws:string,input:FollowUpDraftCreate){const row={workspace_id:ws,follow_up_task_id:input.followUpTaskId,lead_id:input.leadId,company_id:input.companyId,conversation_id:input.conversationId,original_delivery_id:input.originalDeliveryId,sequence_step:input.sequenceStep,purpose:input.purpose,generation_key:input.generationKey,context_version:input.contextVersion,version:input.version,subject:input.subject,body:input.body,status:input.status,confidence:input.confidence,needs_review:input.needsReview,warnings:input.warnings,evidence_refs:input.evidenceRefs,conversation_refs:input.conversationRefs,service_match:input.serviceMatch,portfolio_match:input.portfolioMatch,provider:input.provider,model:input.model,prompt_version:input.promptVersion};const q=await this.client.from('follow_up_drafts').insert(row).select('*').single();if(q.error){if(q.error.code==='23505'){const old=await this.findByGenerationKey(ws,input.generationKey);if(old)return old;}throw new Error(q.error.message);}return map(q.data);}
 async updateStatus(ws:string,id:string,status:FollowUpDraftStatus,actor?:string,reason?:string){const old=await this.findById(ws,id);if(!old)throw new Error('Follow-up draft not found');if(old.status===status)return old;assertFollowUpDraftTransition(old.status,status);if(status==='approved'&&!actor)throw new Error('Authenticated approver required');const now=new Date().toISOString();const values:Record<string,unknown>={status,updated_at:now};if(status==='approved'){values.approved_at=now;values.approved_by=actor;}if(status==='rejected'){values.rejected_at=now;values.rejection_reason=reason??null;}const q=await this.client.from('follow_up_drafts').update(values).eq('workspace_id',ws).eq('id',id).eq('status',old.status).select('*').maybeSingle();if(q.error)throw new Error(q.error.message);return q.data?map(q.data):old;}
 async edit(ws:string,id:string,subject:string,body:string){if(subject.trim().length<1||subject.trim().length>120||body.trim().length<1||body.trim().length>1500)throw new Error('Subject or body is outside allowed limits');const old=await this.findById(ws,id);if(!old||!['draft','ready_for_review'].includes(old.status))throw new Error('Draft is not editable');const history=await this.listByTask(ws,old.followUpTaskId);return this.create(ws,{workspaceId:ws,followUpTaskId:old.followUpTaskId,leadId:old.leadId,companyId:old.companyId,conversationId:old.conversationId,originalDeliveryId:old.originalDeliveryId,sequenceStep:old.sequenceStep,purpose:old.purpose,generationKey:`manual-edit:${old.id}:${history.length+1}`,contextVersion:old.contextVersion,version:Math.max(...history.map(x=>x.version),0)+1,subject:subject.trim(),body:body.trim(),status:'ready_for_review',confidence:old.confidence,needsReview:old.needsReview,warnings:old.warnings,evidenceRefs:old.evidenceRefs,conversationRefs:old.conversationRefs,serviceMatch:old.serviceMatch,portfolioMatch:old.portfolioMatch,provider:old.provider,model:old.model,promptVersion:old.promptVersion});}
 async supersedeActive(ws:string,task:string){for(const row of await this.listByTask(ws,task))if(row.status==='draft'||row.status==='ready_for_review')await this.updateStatus(ws,row.id,'rejected',undefined,'Superseded by regeneration');}
 async recordActivity(ws:string,a:FollowUpDraftActivity){const q=await this.client.from('activities').upsert({workspace_id:ws,lead_id:a.leadId,company_id:a.companyId,actor_kind:a.actorUserId?'operator':'system',actor_user_id:a.actorUserId??null,activity_type:a.activityType,effect_key:a.effectKey,details:{...a.details,...(a.draftId?{draft_id:a.draftId}:{})}},{onConflict:'workspace_id,effect_key',ignoreDuplicates:true});if(q.error)throw new Error(q.error.message);}
}
