import type { SupabaseClient } from '@supabase/supabase-js';
import type { DeliveryRecord, DeliveryStore, PreparedDelivery } from '@client-engine/delivery';
function map(row: Record<string, unknown>): DeliveryRecord { return { workspaceId:String(row.workspace_id), leadId:String(row.lead_id), companyId:String(row.company_id), outreachDraftId:String(row.outreach_draft_id), draftVersion:Number(row.draft_version), recipient:String(row.recipient), subject:String(row.subject), body:String(row.body), channel:'email', provider:'manual', campaignId:row.campaign_id ? String(row.campaign_id) : null, status:row.status as DeliveryRecord['status'], preparedAt:String(row.prepared_at), providerMessageId:row.provider_message_id ? String(row.provider_message_id) : null, providerThreadId:row.provider_thread_id ? String(row.provider_thread_id) : null, id:String(row.id), sentAt:row.sent_at ? String(row.sent_at) : null, sentBy:row.sent_by ? String(row.sent_by) : null, createdAt:String(row.created_at), updatedAt:String(row.updated_at) }; }
export class SupabaseDeliveryStore implements DeliveryStore {
  constructor(private readonly client:SupabaseClient) {}
  async findActive(workspaceId:string,leadId:string,draftId:string,version:number,channel:'email') { const {data,error}=await this.client.from('delivery_records').select('*').eq('workspace_id',workspaceId).eq('lead_id',leadId).eq('outreach_draft_id',draftId).eq('draft_version',version).eq('channel',channel).not('status','in','(failed,cancelled)').maybeSingle(); if(error) throw new Error(error.message); return data ? map(data) : null; }
  async create(workspaceId:string,input:PreparedDelivery) { const {data,error}=await this.client.from('delivery_records').insert({workspace_id:workspaceId,lead_id:input.leadId,company_id:input.companyId,outreach_draft_id:input.outreachDraftId,draft_version:input.draftVersion,campaign_id:input.campaignId,channel:input.channel,provider:input.provider,recipient:input.recipient,subject:input.subject,body:input.body,status:'prepared',prepared_at:input.preparedAt}).select('*').single(); if(error) { if(error.code==='23505') { const existing=await this.findActive(workspaceId,input.leadId,input.outreachDraftId,input.draftVersion,input.channel); if(existing) return existing; } throw new Error(error.message); } return map(data); }
  async markSent(workspaceId:string,id:string,actorId:string) { const current=await this.client.from('delivery_records').select('*').eq('workspace_id',workspaceId).eq('id',id).maybeSingle(); if(current.error) throw new Error(current.error.message); if(!current.data) throw new Error('Delivery not found'); const row=map(current.data); if(row.status==='sent') return row; if(row.status!=='prepared' && row.status!=='draft_created') throw new Error('Delivery is not eligible to mark sent'); const now=new Date().toISOString(); const {data,error}=await this.client.from('delivery_records').update({status:'sent',sent_at:now,sent_by:actorId,updated_at:now}).eq('workspace_id',workspaceId).eq('id',id).eq('status',row.status).select('*').single(); if(error) throw new Error(error.message); const {error:leadError}=await this.client.from('leads').update({stage:'contacted',last_contacted_at:now,updated_at:now}).eq('workspace_id',workspaceId).eq('id',row.leadId).eq('stage','ready'); if(leadError) throw new Error(leadError.message); return map(data); }
  async recordActivity(workspaceId:string,type:'delivery_prepared'|'outreach_marked_sent'|'delivery_cancelled'|'delivery_failed',delivery:DeliveryRecord,actorId?:string) { const {error}=await this.client.from('activities').upsert({workspace_id:workspaceId,lead_id:delivery.leadId,company_id:delivery.companyId,actor_kind:actorId?'operator':'system',actor_user_id:actorId??null,activity_type:type,effect_key:`${type}:${delivery.id}`,details:{delivery_id:delivery.id,draft_id:delivery.outreachDraftId,draft_version:delivery.draftVersion,status:delivery.status}}, {onConflict:'workspace_id,effect_key',ignoreDuplicates:true}); if(error) throw new Error(error.message); }
}
