import { z } from 'zod';
export const deliveryStatusSchema=z.enum(['prepared','draft_created','sent','failed','cancelled']);
export type DeliveryStatus=z.infer<typeof deliveryStatusSchema>;
export const deliveryRequestSchema=z.strictObject({workspaceId:z.string().min(1),leadId:z.string().min(1),companyId:z.string().min(1),outreachDraftId:z.string().min(1),draftVersion:z.number().int().positive(),recipient:z.string().email(),subject:z.string().trim().min(1).max(120),body:z.string().trim().min(1).max(1500),channel:z.literal('email'),provider:z.literal('manual'),campaignId:z.string().nullable().optional()});
export type DeliveryRequest=z.infer<typeof deliveryRequestSchema>;
export type PreparedDelivery=Readonly<DeliveryRequest & {status:'prepared';preparedAt:string;providerMessageId:null;providerThreadId:null}>;
export interface DeliveryProvider { readonly provider:'manual'; prepare(input:DeliveryRequest):Promise<PreparedDelivery>; }
export class ManualDeliveryProvider implements DeliveryProvider { readonly provider='manual' as const; async prepare(input:DeliveryRequest):Promise<PreparedDelivery>{return {...deliveryRequestSchema.parse(input),status:'prepared',preparedAt:new Date().toISOString(),providerMessageId:null,providerThreadId:null};} }
export type DeliveryRecord=Readonly<Omit<PreparedDelivery,'status'|'providerMessageId'|'providerThreadId'> & {id:string;status:DeliveryStatus;providerMessageId:string|null;providerThreadId:string|null;sentAt:string|null;sentBy:string|null;createdAt:string;updatedAt:string}>;
export interface DeliveryStore { findActive(workspaceId:string,leadId:string,draftId:string,version:number,channel:'email'):Promise<DeliveryRecord|null>; create(workspaceId:string,input:PreparedDelivery):Promise<DeliveryRecord>; markSent(workspaceId:string,id:string,actorId:string):Promise<DeliveryRecord>; recordActivity(workspaceId:string,type:'delivery_prepared'|'outreach_marked_sent'|'delivery_cancelled'|'delivery_failed',delivery:DeliveryRecord,actorId?:string):Promise<void>; }
export class DeliveryService { constructor(private readonly provider:DeliveryProvider,private readonly store:DeliveryStore){} async prepare(input:DeliveryRequest){const value=deliveryRequestSchema.parse(input);const existing=await this.store.findActive(value.workspaceId,value.leadId,value.outreachDraftId,value.draftVersion,value.channel);if(existing)return existing;const prepared=await this.provider.prepare(value);const created=await this.store.create(value.workspaceId,prepared);await this.store.recordActivity(value.workspaceId,'delivery_prepared',created);return created;} async markSent(workspaceId:string,id:string,actorId:string){const result=await this.store.markSent(workspaceId,id,actorId);await this.store.recordActivity(workspaceId,'outreach_marked_sent',result,actorId);return result;} }
