'use server';

import { revalidatePath } from 'next/cache';
import { controlledProposalMatch, services } from '@client-engine/ai';
import { dealLossSchema, dealOutcomeSchema, proposalValue } from '../../lib/deal-domain';
import { createClient } from '../../lib/supabase/server';

async function auth() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error('Authentication required'); const { data: member } = await supabase.from('workspace_members').select('workspace_id').eq('user_id', user.id).order('created_at', { ascending: true }).limit(1).maybeSingle(); if (!member?.workspace_id) throw new Error('No authorized workspace'); return { supabase, user, workspaceId: String(member.workspace_id) }; }
const result = (error?: unknown) => error ? { ok: false as const, error: error instanceof Error ? error.message : 'Unable to update deal' } : { ok: true as const };
function refresh(leadId?: unknown) { revalidatePath('/deals'); revalidatePath('/dashboard'); revalidatePath('/proposals'); if (typeof leadId === 'string') revalidatePath(`/leads/${leadId}`); }
async function activity(a: Awaited<ReturnType<typeof auth>>, type: string, deal: Record<string, unknown>, details: Record<string, unknown>) { const { error } = await a.supabase.from('activities').upsert({ workspace_id: a.workspaceId, lead_id: deal.lead_id, company_id: deal.company_id, deal_id: deal.id, actor_kind: 'operator', actor_user_id: a.user.id, activity_type: type, effect_key: `${type}:${deal.id}`, details: { deal_id: deal.id, proposal_id: deal.proposal_id, status: deal.status, ...details } }, { onConflict: 'workspace_id,effect_key', ignoreDuplicates: true }); if (error) throw new Error(error.message); }

export async function createDealAction(proposalId: string) { try { const a = await auth(); const { data: proposal } = await a.supabase.from('proposals').select('*').eq('workspace_id', a.workspaceId).eq('id', proposalId).maybeSingle(); if (!proposal || proposal.status !== 'approved') throw new Error('Only approved proposals can create an open deal'); const { data: existing } = await a.supabase.from('deals').select('*').eq('workspace_id', a.workspaceId).eq('proposal_id', proposalId).maybeSingle(); if (existing) return { ...result(), dealId: existing.id }; const [{ data: lead }, { data: company }, { data: meeting }] = await Promise.all([a.supabase.from('leads').select('id,name,company_id,source').eq('workspace_id', a.workspaceId).eq('id', proposal.lead_id).maybeSingle(), a.supabase.from('companies').select('name,research_output').eq('workspace_id', a.workspaceId).eq('id', proposal.company_id).maybeSingle(), a.supabase.from('meetings').select('campaign_id').eq('workspace_id', a.workspaceId).eq('id', proposal.meeting_id).maybeSingle()]); if (!lead || String(lead.company_id) !== String(proposal.company_id)) throw new Error('Proposal lead relationship is invalid'); const research = (company?.research_output ?? {}) as Record<string, unknown>; const matchedService = controlledProposalMatch(typeof research.recommendedService === 'string' ? research.recommendedService : null, null).service; const serviceId = services.find((service) => service.id === matchedService || service.label === matchedService)?.id ?? null; const proposalAmount = proposalValue(proposal.pricing); const row = { workspace_id: a.workspaceId, company_id: proposal.company_id, lead_id: proposal.lead_id, proposal_id: proposal.id, meeting_id: proposal.meeting_id, campaign_id: meeting?.campaign_id ?? null, name: `${String(company?.name ?? lead.name)} — ${String(proposal.title)}`, status: 'open', value: proposalAmount?.value ?? null, proposal_value: proposalAmount?.value ?? null, currency: proposalAmount?.currency ?? 'USD', pricing_mode: typeof (proposal.pricing as Record<string, unknown>).mode === 'string' ? (proposal.pricing as Record<string, unknown>).mode : 'UNPRICED', source: lead.source, service_id: serviceId, portfolio_match: null, created_by: a.user.id }; const { data, error } = await a.supabase.from('deals').insert(row).select('*').single(); if (error) { if (error.code === '23505') { const { data: duplicate } = await a.supabase.from('deals').select('id').eq('workspace_id', a.workspaceId).eq('proposal_id', proposalId).maybeSingle(); if (duplicate) return { ...result(), dealId: duplicate.id }; } throw new Error(error.message); } await activity(a, 'deal_created', data, { value: data.value, currency: data.currency, service_id: data.service_id ?? 'UNKNOWN' }); refresh(proposal.lead_id); return { ...result(), dealId: data.id }; } catch (error) { return result(error); } }

export async function markDealWonAction(input: unknown) { try { const a = await auth(); const value = dealOutcomeSchema.parse(input); const { data: deal } = await a.supabase.from('deals').select('*').eq('workspace_id', a.workspaceId).eq('id', value.dealId).maybeSingle(); if (!deal) throw new Error('Deal not found'); if (deal.status === 'won') return result(); if (deal.status !== 'open' || !deal.proposal_id) throw new Error('Only open proposal-backed deals can be marked won'); const { data: proposal } = await a.supabase.from('proposals').select('id,status').eq('workspace_id', a.workspaceId).eq('id', deal.proposal_id).maybeSingle(); if (!proposal || proposal.status !== 'approved') throw new Error('Deal proposal is not approved'); const now = new Date().toISOString(); const { data: updated, error } = await a.supabase.from('deals').update({ status: 'won', value: value.value, currency: value.currency, won_at: now, closed_at: now, closed_by: a.user.id, updated_at: now }).eq('workspace_id', a.workspaceId).eq('id', deal.id).eq('status', 'open').select('*').maybeSingle(); if (error) throw new Error(error.message); if (!updated) { const { data: current } = await a.supabase.from('deals').select('status').eq('workspace_id', a.workspaceId).eq('id', deal.id).maybeSingle(); if (current?.status === 'won') return result(); throw new Error('Deal state changed; refresh and try again'); } await a.supabase.from('leads').update({ stage: 'won', updated_at: now }).eq('workspace_id', a.workspaceId).eq('id', deal.lead_id).eq('stage', 'proposal'); await activity(a, 'deal_won', updated, { previous_status: 'open', value: updated.value, currency: updated.currency }); refresh(deal.lead_id); return result(); } catch (error) { return result(error); } }

export async function markDealLostAction(input: unknown) { try { const a = await auth(); const value = dealLossSchema.parse(input); const { data: deal } = await a.supabase.from('deals').select('*').eq('workspace_id', a.workspaceId).eq('id', value.dealId).maybeSingle(); if (!deal) throw new Error('Deal not found'); if (deal.status === 'lost') return result(); if (deal.status !== 'open') throw new Error('Only open deals can be marked lost'); const now = new Date().toISOString(); const { data: updated, error } = await a.supabase.from('deals').update({ status: 'lost', lost_at: now, closed_at: now, closed_by: a.user.id, loss_reason: value.reason, loss_notes: value.notes?.trim() || null, updated_at: now }).eq('workspace_id', a.workspaceId).eq('id', deal.id).eq('status', 'open').select('*').maybeSingle(); if (error) throw new Error(error.message); if (!updated) { const { data: current } = await a.supabase.from('deals').select('status').eq('workspace_id', a.workspaceId).eq('id', deal.id).maybeSingle(); if (current?.status === 'lost') return result(); throw new Error('Deal state changed; refresh and try again'); } await a.supabase.from('leads').update({ stage: 'lost', updated_at: now }).eq('workspace_id', a.workspaceId).eq('id', deal.lead_id).eq('stage', 'proposal'); await activity(a, 'deal_lost', updated, { previous_status: 'open', loss_reason: updated.loss_reason }); refresh(deal.lead_id); return result(); } catch (error) { return result(error); } }
