'use server';
import { revalidatePath } from 'next/cache';
import { DeliveryService, ManualDeliveryProvider } from '@client-engine/delivery';
import { SupabaseDeliveryStore } from '@client-engine/database';
import { createClient } from '../../lib/supabase/server';
import { createFollowUpsForSent } from './follow-ups';
import { canFollowUp } from '@client-engine/conversations';
import { cancellationReasonFor } from '@client-engine/follow-ups';
import { loadFollowUpEligibility } from './follow-ups';

async function authorize() { const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error('Authentication required'); const {data:member,error}=await supabase.from('workspace_members').select('workspace_id').eq('user_id',user.id).order('created_at',{ascending:true}).limit(1).maybeSingle(); if(error||!member?.workspace_id) throw new Error('No authorized workspace'); return {supabase,user,workspaceId:String(member.workspace_id)}; }
function result(error?:unknown){return error?{ok:false,error:error instanceof Error?error.message:'Unable to update delivery'}:{ok:true};}
export async function prepareDeliveryAction(draftId:string){try{const {supabase,workspaceId}=await authorize();const {data:draft}=await supabase.from('outreach_drafts').select('*').eq('workspace_id',workspaceId).eq('id',draftId).maybeSingle();if(!draft||draft.status!=='approved')throw new Error('Only approved drafts can be prepared');const {data:lead}=await supabase.from('leads').select('id,company_id,email,do_not_contact').eq('workspace_id',workspaceId).eq('id',draft.lead_id).maybeSingle();if(!lead)throw new Error('Lead not found');if(lead.do_not_contact)throw new Error('Lead is suppressed');if(!lead.email)throw new Error('Lead has no recipient email');const service=new DeliveryService(new ManualDeliveryProvider(),new SupabaseDeliveryStore(supabase));await service.prepare({workspaceId,leadId:String(lead.id),companyId:String(lead.company_id??draft.company_id),outreachDraftId:String(draft.id),draftVersion:Number(draft.version),recipient:String(lead.email),subject:String(draft.subject),body:String(draft.body),channel:'email',provider:'manual',campaignId:draft.campaign_id?String(draft.campaign_id):null});revalidatePath('/outreach');return result();}catch(error){return result(error);}}
export async function markDeliverySentAction(deliveryId:string){try{const {supabase,user,workspaceId}=await authorize();const store=new SupabaseDeliveryStore(supabase);const {data:delivery}=await supabase.from('delivery_records').select('*').eq('workspace_id',workspaceId).eq('id',deliveryId).maybeSingle();if(!delivery)throw new Error('Delivery not found');await new DeliveryService(new ManualDeliveryProvider(),store).markSent(workspaceId,deliveryId,user.id);const {error:conversationError}=await supabase.from('conversations').upsert({workspace_id:workspaceId,lead_id:delivery.lead_id,campaign_id:delivery.campaign_id??null,delivery_id:deliveryId,channel:'email',provider:'manual',status:'open'},{onConflict:'workspace_id,lead_id,channel'});if(conversationError)throw new Error(conversationError.message);await createFollowUpsForSent({supabase,user,workspaceId},deliveryId);revalidatePath('/outreach');revalidatePath('/follow-ups');revalidatePath(`/leads/${delivery.lead_id}`);return result();}catch(error){return result(error);}}

async function followUpEligibility(a:Awaited<ReturnType<typeof authorize>>, task:Record<string,unknown>){const value=await loadFollowUpEligibility(a,{leadId:String(task.lead_id),conversationId:String(task.conversation_id),deliveryId:String(task.delivery_id),campaignId:task.campaign_id?String(task.campaign_id):null});if(canFollowUp(value))return value;const reason=cancellationReasonFor(value)??'OTHER';await a.supabase.from('follow_up_tasks').update({status:'cancelled',cancellation_reason:reason,eligibility_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('workspace_id',a.workspaceId).eq('id',task.id).eq('status','due');throw new Error(`Follow-up is no longer eligible: ${reason}`);}
export async function prepareFollowUpDeliveryAction(draftId:string){try{const a=await authorize();const {data:draft}=await a.supabase.from('follow_up_drafts').select('*').eq('workspace_id',a.workspaceId).eq('id',draftId).maybeSingle();if(!draft||draft.status!=='approved')throw new Error('Only approved follow-up drafts can be prepared');const {data:task}=await a.supabase.from('follow_up_tasks').select('*').eq('workspace_id',a.workspaceId).eq('id',draft.follow_up_task_id).maybeSingle();if(!task||task.status!=='due')throw new Error('Follow-up task is not due');await followUpEligibility(a,task);const {data:lead}=await a.supabase.from('leads').select('id,email,company_id').eq('workspace_id',a.workspaceId).eq('id',draft.lead_id).maybeSingle();if(!lead?.email)throw new Error('Lead has no recipient email');const {data:existing}=await a.supabase.from('delivery_records').select('id').eq('workspace_id',a.workspaceId).eq('follow_up_task_id',task.id).eq('follow_up_draft_id',draft.id).eq('draft_version',draft.version).eq('channel','email').not('status','in','(failed,cancelled)').maybeSingle();if(!existing){const {error}=await a.supabase.from('delivery_records').insert({workspace_id:a.workspaceId,lead_id:lead.id,company_id:lead.company_id,follow_up_task_id:task.id,follow_up_draft_id:draft.id,draft_version:draft.version,conversation_id:task.conversation_id,sequence_step:task.sequence_step,purpose:task.purpose,campaign_id:task.campaign_id,channel:'email',provider:'manual',recipient:lead.email,subject:draft.subject,body:draft.body,status:'prepared',prepared_at:new Date().toISOString()});if(error)throw new Error(error.message);}const {data:delivery}=await a.supabase.from('delivery_records').select('id').eq('workspace_id',a.workspaceId).eq('follow_up_task_id',task.id).eq('follow_up_draft_id',draft.id).eq('draft_version',draft.version).maybeSingle();if(delivery)await a.supabase.from('activities').upsert({workspace_id:a.workspaceId,lead_id:lead.id,company_id:lead.company_id,actor_kind:'operator',actor_user_id:a.user.id,activity_type:'follow_up_delivery_prepared',effect_key:`follow_up_delivery_prepared:${delivery.id}`,details:{delivery_id:delivery.id,follow_up_task_id:task.id,follow_up_draft_id:draft.id,version:draft.version,sequence_step:task.sequence_step,purpose:task.purpose}},{onConflict:'workspace_id,effect_key',ignoreDuplicates:true});revalidatePath('/follow-ups');return result();}catch(error){return result(error);}}
export async function markFollowUpDeliverySentAction(deliveryId:string){try{const a=await authorize();const {data:delivery}=await a.supabase.from('delivery_records').select('*').eq('workspace_id',a.workspaceId).eq('id',deliveryId).maybeSingle();if(!delivery?.follow_up_task_id||!delivery.follow_up_draft_id)throw new Error('Follow-up delivery not found');if(delivery.status==='sent')return result();if(delivery.status!=='prepared')throw new Error('Delivery is not prepared');const {data:task}=await a.supabase.from('follow_up_tasks').select('*').eq('workspace_id',a.workspaceId).eq('id',delivery.follow_up_task_id).maybeSingle();const {data:draft}=await a.supabase.from('follow_up_drafts').select('id,status').eq('workspace_id',a.workspaceId).eq('id',delivery.follow_up_draft_id).maybeSingle();if(!task||task.status!=='due'||draft?.status!=='approved')throw new Error('Follow-up delivery is no longer eligible');await followUpEligibility(a,task);const now=new Date().toISOString();const {error:deliveryError}=await a.supabase.from('delivery_records').update({status:'sent',sent_at:now,sent_by:a.user.id,updated_at:now}).eq('workspace_id',a.workspaceId).eq('id',deliveryId).eq('status','prepared');if(deliveryError)throw new Error(deliveryError.message);const {error:taskError}=await a.supabase.from('follow_up_tasks').update({status:'completed',completed_at:now,updated_at:now}).eq('workspace_id',a.workspaceId).eq('id',task.id).eq('status','due');if(taskError)throw new Error(taskError.message);await a.supabase.from('messages').upsert({workspace_id:a.workspaceId,conversation_id:task.conversation_id,lead_id:delivery.lead_id,campaign_id:task.campaign_id??null,direction:'outbound',message_type:'manual',status:'draft',provider:'manual',subject:delivery.subject,body:delivery.body,recipient_email:delivery.recipient,sequence_step:null,idempotency_key:`follow_up_delivery:${deliveryId}`,raw_metadata:{delivery_id:deliveryId,follow_up_task_id:task.id,follow_up_draft_id:draft.id}},{onConflict:'workspace_id,idempotency_key',ignoreDuplicates:true});await a.supabase.from('activities').upsert([{workspace_id:a.workspaceId,lead_id:delivery.lead_id,company_id:delivery.company_id,actor_kind:'operator',actor_user_id:a.user.id,activity_type:'follow_up_marked_sent',effect_key:`follow_up_marked_sent:${deliveryId}`,details:{delivery_id:deliveryId,follow_up_task_id:task.id}},{workspace_id:a.workspaceId,lead_id:delivery.lead_id,company_id:delivery.company_id,actor_kind:'system',activity_type:'follow_up_task_completed',effect_key:`follow_up_task_completed:${task.id}`,details:{delivery_id:deliveryId,follow_up_task_id:task.id}}],{onConflict:'workspace_id,effect_key',ignoreDuplicates:true});revalidatePath('/follow-ups');revalidatePath(`/leads/${delivery.lead_id}`);return result();}catch(error){return result(error);}}
